---
- name: Delete previous entries
  become: True
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.ipaddress }}.*"
    state: absent
  with_items: "{{ etc_hosts }}"
  when: etc_hosts is defined

- name: Set /etc/hosts
  become: True
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.ipaddress }}.*"
    line: "{{ '%-15s' | format(item.ipaddress) }} {{ item.hostname }} {{ item.aliases | default([]) | join(' ') }}"
    state: present
  with_items: "{{ etc_hosts }}"
  when: etc_hosts is defined
